title: Mani Vardhan Reddy Papagari
description: Software Engineer | .NET Core â€¢ Azure â€¢ API Development
ğŸ“ Hyderabad â€¢ ğŸ“ 9121471194 â€¢ âœ‰ï¸ [manivardhanreddy82@gmail.com](mailto:manivardhanreddy82@gmail.com)
theme: jekyll-theme-minimal
