title: "Mani Vardhan Reddy Papagari"
description: "Software Engineer | .NET Core â€¢ Azure â€¢ API Development"
contact_info: "ğŸ“ Hyderabad â€¢ ğŸ“ 9121471194 â€¢ âœ‰ï¸ manivardhanreddy82@gmail.com"
theme: jekyll-theme-minimal
